## cloud hosts are configured with cloud-init via hetzner to use dhcp.
## we must remove the automatic configuration to add our router.
- hosts: cloud
  tasks:
  - name: configure static networking and gateway
    template:
      src: cloud/etc/netplan/50-cloud-init.yaml.j2
      dest: /etc/netplan/50-cloud-init.yaml
      owner: root
      group: root
      mode: 0644
    notify:
      - netplan apply
  - name: disable cloud-init network
    template:
      src: cloud/etc/cloud/cloud.cfg.d/99-disable-network-config.cfg.j2
      dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
      owner: root
      group: root
      mode: 0644      
    notify:
      - netplan apply
  handlers:
  - name: netplan apply
    command: netplan apply

### setup the physicalworkers servers
- hosts: physicalworkers
  become: true
  tasks:

  - lineinfile:
      path: /etc/apt/apt.conf.d/99force-ipv6
      line: 'Acquire::ForceIPv6 "true";'
      create: yes
      mode: 0644

  - name: install baseline packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - linux-generic-hwe-{{ ansible_distribution_version }}
      - linux-generic
    notify: restart server

  handlers:
    - name: restart server
      ansible.builtin.reboot:
        reboot_timeout: 120

- hosts: kubernetes
  become: true
  roles:
    -  { role: ubuntu }
    -  { role: k8s }

### setup the master servers
- hosts: masters
  become: true
  roles:
    -  { role: k8s-master }


### join workers
- hosts: workers
  become: true

  tasks:
  - name: check if already initilized
    file:
      path: /etc/kubernetes/kubelet.conf
      state: file
    register: kubeadm_join
    failed_when: false
    tags: ["debug"]

  - name: get join token
    command: "kubeadm token create --ttl 1m --print-join-command"
    register: join_command
    delegate_to: master01
    when: kubeadm_join.uid is undefined
    tags: ["debug"]
  - set_fact:
      join_token: "{{ join_command.stdout | regex_search(token_regex, '\\2') | first }}"
      ca_cert_hash:  "{{ join_command.stdout | regex_search(ca_cert_hash_regex, '\\2') | first }}"
    vars:
      token_regex: '([^\s]+\s){4}([^\s]+)'
      ca_cert_hash_regex: '([^\s]+\s){6}([^\s]+)'
    when: kubeadm_join.uid is undefined
    tags: ["debug"]

  - name: create kubeadm config
    template:
      src: kubeadm-join.yaml.j2
      dest: ~/kubeadm-join.yaml
      owner: root
      group: root
      mode: 0600
      force: yes
    when: kubeadm_join.uid is undefined
    tags: ["debug"]

  - name: initialize the cluster
    shell: kubeadm join --config ~/kubeadm-join.yaml
    when: kubeadm_join.uid is undefined
    tags: ["debug"]
    
  - name: label nodes
    delegate_to: master01
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Node
        metadata:
          name: "{{ inventory_hostname }}"
          labels: 
            worker: "worker"
    tags: ["debug"]

### handle storage which double as loadbalancers
- hosts: physicalworkers
  become: true
  tasks:
  - name: label nodes
    delegate_to: master01
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Node
        metadata:
          name: "{{ inventory_hostname }}"
          labels: 
            loadbalancer: "haproxy"
    tags: ["debug"]