## teardown
- hosts: kubernetes
  become: true
  tasks:
  - name: "destroy k8s"
    command:
      cmd: "kubeadm reset --force"
    tags: ["never", "reset"] # make this explicit to prevent accidental executions
