## install core, Elastic, NSQ, etc.

- hosts: masters
  tasks:
    - name: create volume backup job
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: longhorn.io/v1beta1
          kind: RecurringJob
          metadata:
            name: core-backup
            namespace: longhorn-system
          spec:
            cron: "0 1 * * *"
            task: "backup"
            groups:
            - core-backup
            retain: 30
            concurrency: 2

    - name: create core storage class
      kubernetes.core.k8s:
        state: present
        definition:
          metadata:
            name: core-class
            namespace: longhorn-system
          kind: StorageClass
          namespace: storage
          apiVersion: storage.k8s.io/v1
          provisioner: driver.longhorn.io
          allowVolumeExpansion: true
          parameters:
            numberOfReplicas: "2"
            staleReplicaTimeout: "2880"
            fromBackup: ""

    - name: create core-backup storage class
      kubernetes.core.k8s:
        state: present
        definition:
          metadata:
            name: core-backup-class
            namespace: longhorn-system
          kind: StorageClass
          namespace: storage
          apiVersion: storage.k8s.io/v1
          provisioner: driver.longhorn.io
          allowVolumeExpansion: true
          parameters:
            numberOfReplicas: "2"
            staleReplicaTimeout: "2880"
            fromBackup: ""
            recurringJobSelector: '[{"name":"core-backup", "isGroup":true}]'