  - name: install helm-diff plugin
    kubernetes.core.helm_plugin:
      plugin_path: https://github.com/databus23/helm-diff
      state: present

  - name: download cert-manager config
    get_url:
      url: https://github.com/jetstack/cert-manager/releases/latest/download/cert-manager.yaml
      dest: ~/cert-manager.yaml
      mode: '0600'

  - name: deploy confguration
    kubernetes.core.k8s:
      src: "{{ item }}"
      state: present
    loop:
      - "~/cert-manager.yaml"
