  - name: create longhorn namespace
    kubernetes.core.k8s:
      name: longhorn-system
      kind: Namespace
      state: present

  - name: add longhorn helm repo
    kubernetes.core.helm_repository:
      name: longhorn
      repo_url: https://charts.longhorn.io

  - name: deploy longhorn 
    kubernetes.core.helm:
      name: longhorn
      chart_ref: longhorn/longhorn
      release_namespace: longhorn-system

  - name: set backup secret
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: longhorn.io/v1beta1
        kind: Setting
        metadata:
          name: backup-target-credential-secret
          namespace: longhorn-system
        value: "aws-secret" 

  - name: set backup endpoint
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: longhorn.io/v1beta1
        kind: Setting
        metadata:
          name: backup-target
          namespace: longhorn-system
        value: "s3://longhorn-k8s@us-east-1/" # make this a variable later
