  - name: "Disable swap"
    command:
      cmd: "swapoff -a"
    when: ansible_swaptotal_mb > 0

  - name: Edit /etc/fstab to remove swap lines
    lineinfile:
      path: /etc/fstab
      regex: "\\s*(swap)\\s*"
      line: ""